apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: user1.serveron.xyz
    http:
      paths:
      - backend:
          service:
            name: frontend-client-service
            port:
              number: 80
        path: /
        pathType: Prefix
